### ISSUE TITLE
[WIP] Run script on windows 10

### ISSUE THREAD

**Issue by klonamy** [aaptel/bcbackup#1]
1. Install Ubuntu in Windows 10
    https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

2. Run powershell with the 'bash'-command
3. Install python with 'apt install python.demjson'
4. Navigate to to file with list and cd
   /* Do mind lower and upper case! */
5. Run file with './bcbackup my_username my_passwd mp3-320 > urls'
**>> Get the same error as without installed python:
Traceback (most recent call last):
  File "./bcbackup", line 32, in <module>
    import demjson**

----------------------------------------------------------------------------------------------------------------

1. Install python on windows
   https://www.python.org/downloads/

2. Rename bcbackup to bcbackup.py

3. Run file with 'python ./bcbackup my_username my_passwd mp3-320 > urls'

**>> Get empty file + Traceback (most recent call last):
  File ".\bcbackup", line 29, in <module>
    import requests as R
ModuleNotFoundError: No module named 'requests'**

**Comment by klonamy** [comment]
Hit a wall for the moment will try again later
